const circles={builders:{number:'01',symbol:'</>',kicker:'TECH ORBIT BUILDERS',title:'Less “what if”.\nMore “let’s build”.',description:'Find collaborators, exchange feedback, and turn real-world problems into projects. Bring an idea, a skill, or the willingness to figure it out together.',tags:['Projects','Collaboration','Feedback']},learning:{number:'02',symbol:'✳',kicker:'TECH ORBIT LEARNING CIRCLE',title:'Stay curious.\nLearn together.',description:'Ask the question, share the resource, and learn from someone with a different perspective. From your first steps to your next breakthrough, learning is better with company.',tags:['Resources','Questions','Skill sharing']},general:{number:'03',symbol:'+',kicker:'GENERAL',title:'People first.\nConnections next.',description:'Introduce yourself, exchange perspectives, and meet people beyond your usual circle. Developers, analysts, designers, students, and professionals from other fields belong in the conversation.',tags:['Introductions','Discussion','Connections']},announcements:{number:'04',symbol:'◎',kicker:'ANNOUNCEMENTS',title:'Keep up with\nyour community.',description:'Follow community updates and announcements from the admins. Keep an eye here for shared plans, discussion opportunities, and meeting details as they are announced.',tags:['Community updates','Admin announcements','Meeting plans']}};
const tabs=[...document.querySelectorAll('[data-circle]')];function selectCircle(tab){const data=circles[tab.dataset.circle];tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',selected);t.tabIndex=selected?0:-1});document.getElementById('circle-detail').setAttribute('aria-labelledby',tab.id);document.getElementById('circle-kicker').textContent=data.kicker;const title=document.getElementById('circle-title');title.replaceChildren();data.title.split('\n').forEach((line,i)=>{if(i)title.append(document.createElement('br'));title.append(document.createTextNode(line))});document.getElementById('circle-description').textContent=data.description;const number=document.querySelector('.circle-number');number.replaceChildren(document.createTextNode(data.number));const symbol=document.createElement('span');symbol.textContent=data.symbol;number.append(symbol);const tags=document.getElementById('circle-tags');tags.replaceChildren(...data.tags.map(text=>{const s=document.createElement('span');s.textContent=text;return s}))}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectCircle(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(i+1)%tabs.length;if(event.key==='ArrowLeft')next=(i-1+tabs.length)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();tabs[next].focus();selectCircle(tabs[next])}})});
document.getElementById('share-button').addEventListener('click',async()=>{const link='https://chat.whatsapp.com/DScUdJlVTf11HXQwdzAbPg';const status=document.getElementById('share-status');const text='Join Tech Orbit Hub — a Kerala-rooted community to learn, collaborate, and build together.';try{if(navigator.share){await navigator.share({title:'Tech Orbit Hub',text,url:link});status.textContent='';return}if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text+' '+link);status.textContent='Community invite copied. Share it with your people.'}else{status.textContent='Share this invite: '+link}}catch(error){if(error.name!=='AbortError')status.textContent='Share this invite: '+link}});
const menuToggle=document.querySelector('.menu-toggle');const navigation=document.getElementById('main-navigation');function closeMenu(){menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Open navigation');navigation.classList.remove('is-open')}
menuToggle.addEventListener('click',()=>{const opened=menuToggle.getAttribute('aria-expanded')!=='true';menuToggle.setAttribute('aria-expanded',String(opened));menuToggle.setAttribute('aria-label',opened?'Close navigation':'Open navigation');navigation.classList.toggle('is-open',opened)});
navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menuToggle.getAttribute('aria-expanded')==='true'){closeMenu();menuToggle.focus()}});
if('IntersectionObserver' in window){const stickyJoin=document.querySelector('.mobile-join');new IntersectionObserver(entries=>{stickyJoin.classList.toggle('is-visible',!entries[0].isIntersecting)},{threshold:0}).observe(document.querySelector('.hero-actions'));if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.mission,.section-heading,.contribution-grid article,.faq').forEach(element=>{element.classList.add('reveal');observer.observe(element)})}}
// Continuous motion stays decorative; all content remains accessible without it.
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');const track=document.querySelector('.discipline-track');if(track&&!reducedMotion.matches){const clone=document.createElement('span');clone.className='marquee-copy';clone.setAttribute('aria-hidden','true');clone.style.display='contents';clone.innerHTML=track.innerHTML;track.append(clone)}
let scrollFrame=false;function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--progress',max>0?String(scrollY/max):'0');scrollFrame=false}window.addEventListener('scroll',()=>{if(!scrollFrame){scrollFrame=true;requestAnimationFrame(updateProgress)}},{passive:true});updateProgress();window.addEventListener('resize',updateProgress,{passive:true});
const art=document.querySelector('.hero-art');if(art&&window.matchMedia('(hover: hover) and (pointer: fine)').matches&&!reducedMotion.matches){art.addEventListener('pointermove',event=>{const r=art.getBoundingClientRect();art.style.setProperty('--tilt-x',((event.clientX-r.left)/r.width-.5)*10+'deg');art.style.setProperty('--tilt-y',-((event.clientY-r.top)/r.height-.5)*8+'deg')});art.addEventListener('pointerleave',()=>{art.style.setProperty('--tilt-x','0deg');art.style.setProperty('--tilt-y','0deg')})}
tabs.forEach(tab=>tab.addEventListener('click',()=>{const panel=document.getElementById('circle-detail');panel.classList.remove('circle-switch');requestAnimationFrame(()=>panel.classList.add('circle-switch'))}));
if('IntersectionObserver' in window){const activeNav=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navigation.querySelectorAll('a').forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')==='#'+entry.target.id))}}),{rootMargin:'-15% 0px -60% 0px',threshold:0});document.querySelectorAll('#about,#circles,#contribute').forEach(section=>activeNav.observe(section))}
